@file:JvmName("FetchErrorStrings")

package com.tonyodev.fetch2core

const val DOWNLOAD_NOT_FOUND = "fetch download not found"
const val FAILED_TO_ENQUEUE_REQUEST = "UNIQUE constraint failed: requests._id (code 1555)"
const val FAILED_TO_ENQUEUE_REQUEST_FILE_FOUND = "UNIQUE constraint failed: requests._file (code 2067)"
const val EMPTY_RESPONSE_BODY = "empty_response_body"
const val RESPONSE_NOT_SUCCESSFUL = "request_not_successful"
const val UNKNOWN_ERROR = "unknown"
const val FNC = "FNC"
const val ENOENT = "open failed: ENOENT (No such file or directory)"
const val ETIMEDOUT = "recvfrom failed: ETIMEDOUT (Connection timed out)"
const val IO404 = "java.io.IOException: 404"
const val NO_ADDRESS_HOSTNAME = "No address associated with hostname"
const val CONNECTION_TIMEOUT = "timeout"
const val HOST_RESOLVE_ISSUE = "Unable to resolve host"
const val EACCES = "open failed: EACCES (Permission denied)"
const val ENOSPC = "write failed: ENOSPC (No space left on device)"
const val DATABASE_DISK_FULL = "database or disk is full (code 13)"
const val FETCH_DATABASE_ERROR = "Fetch data base error"
const val UNIQUE_ID_DATABASE = "UNIQUE constraint failed: requests._id"
const val FAILED_TO_CONNECT = "Failed to connect"
const val SOFTWARE_ABORT_CONNECTION = "Software caused connection abort"
const val READ_TIME_OUT = "Read timed out at"
const val GLOBAL_FETCH_CONFIGURATION_NOT_SET = "Global Fetch Configuration not set"
const val INVALID_CONTENT_HASH = "invalid content hash"
const val REQUEST_WITH_FILE_PATH_ALREADY_EXIST = "request_with_file_path_already_exist"
const val DOWNLOAD_INCOMPLETE = "download_incomplete"
const val FAILED_TO_UPDATE_REQUEST = "failed_to_update_request"
const val FAILED_TO_ADD_COMPLETED_DOWNLOAD = "failed_to_add_completed_download"
const val FETCH_FILE_SERVER_INVALID_RESPONSE_TYPE = "fetch_file_server_invalid_response_type"
const val REQUEST_DOES_NOT_EXIST = "request_does_not_exist"
const val NO_NETWORK_CONNECTION = "no_network_connection"
const val FILE_NOT_FOUND = "file_not_found"
const val FETCH_FILE_SERVER_URL_INVALID = "fetch_file_server_url_invalid"
const val ENQUEUED_REQUESTS_ARE_NOT_DISTINCT = "request_list_not_distinct"
const val ENQUEUE_NOT_SUCCESSFUL = "enqueue_not_successful"
const val AWAIT_CALL_ON_UI_THREAD = "await_call_on_ui_thread"
const val BLOCKING_CALL_ON_UI_THREAD = "blocking_call_on_ui_thread"
const val FILE_CANNOT_BE_RENAMED = "file_cannot_be_renamed"
const val FAILED_RENAME_FILE_ASSOCIATED_WITH_INCOMPLETE_DOWNLOAD = "cannot rename file associated with incomplete download"
const val FILE_ALLOCATION_ERROR = "file_allocation_error"