package com.tonyodev.fetch2.fetch

import android.content.Context
import com.tonyodev.fetch2.Downloader
import com.tonyodev.fetch2.Logger
import com.tonyodev.fetch2.NetworkType

/** This class holds preferences generated by a FetchBuilder object.*/
class FetchBuilderPrefs(val appContext: Context,
                        val namespace: String,
                        val concurrentLimit: Int,
                        val progressReportingIntervalMillis: Long,
                        val downloadBufferSizeBytes: Int,
                        val loggingEnabled: Boolean,
                        val inMemoryDatabaseEnabled: Boolean,
                        val downloader: Downloader,
                        val globalNetworkType: NetworkType,
                        val logger: Logger,
                        val autoStart: Boolean,
                        val retryOnNetworkGain: Boolean)